### ISSUE TITLE
The demo bug in CalAbs

### ISSUE THREAD

**Issue by PeterJaq** [marcus-cmc/Optical-Modeling#1]
I check the demo, but meet the follow bug in def CalAbs line 314:

self.AbsRate[posind[0]:posind[1]] *= ( a[mater] * np.real(self.nk[mater]))

Traceback (most recent call last):
  File "C:/Users/anqin/PycharmProjects/Optical-Modeling2/RunModeling.py", line 109, in <module>
    figformat='pdf', savename=SaveName)
  File "C:\Users\anqin\PycharmProjects\Optical-Modeling2\TransferMatrix.py", line 89, in RunSim
    self.CalAbs()
  File "C:\Users\anqin\PycharmProjects\Optical-Modeling2\TransferMatrix.py", line 314, in CalAbs
    a[mater] * np.real(self.nk[mater]))
  File "C:\Users\anqin\AppData\Local\Continuum\anaconda3\envs\Optical-Modeling2\lib\site-packages\pandas\core\ops.py", line 1068, in wrapper
    index=left.index, name=res_name, dtype=None)
  File "C:\Users\anqin\AppData\Local\Continuum\anaconda3\envs\Optical-Modeling2\lib\site-packages\pandas\core\ops.py", line 977, in _construct_result
    out = left._constructor(result, index=index, dtype=dtype)
  File "C:\Users\anqin\AppData\Local\Continuum\anaconda3\envs\Optical-Modeling2\lib\site-packages\pandas\core\series.py", line 261, in __init__
    .format(val=len(data), ind=len(index)))
ValueError: Length of passed values is 145, index implies 426

It seems not work. Can you give me any suggest to fix this problem?

**Comment by marcus-cmc** [comment]
Seems to be some compatibility issue (python 2 and python 3). Fixed. Try it again.
